# Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres/db/data_e2e_auth-keycloak_without-application-admin:/var/lib/postgresql/data
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
  horusec-auth:
    build:
      context: ../../../
      dockerfile: ./horusec-auth/deployments/Dockerfile
    ports:
      - "8006:8006"
      - "8007:8007"
    depends_on:
      - "postgresql"
    restart: always
    container_name: horusec-auth
    environment:
      HORUSEC_PORT: "8006"
      HORUSEC_GRPC_PORT: "8007"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret"
      HORUSEC_ENABLE_APPLICATION_ADMIN: "false"
      HORUSEC_AUTH_TYPE: "horusec"
      HORUSEC_DISABLED_BROKER: "true"
  horusec-account:
    build:
      context: ../../../
      dockerfile: ./horusec-account/deployments/Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - "postgresql"
      - "horusec-auth"
    restart: always
    container_name: horusec-account
    environment:
      HORUSEC_PORT: "8003"
      HORUSEC_DISABLED_BROKER: "true"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_GRPC_AUTH_URL: "horusec-auth:8007"
  horusec-analytic:
    build:
      context: ../../../
      dockerfile: ./horusec-analytic/deployments/Dockerfile
    ports:
      - "8005:8005"
    depends_on:
      - "postgresql"
    restart: always
    container_name: horusec-analytic
    environment:
      HORUSEC_PORT: "8005"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_GRPC_AUTH_URL: "horusec-auth:8007"
  horusec-api:
    build:
      context: ../../../
      dockerfile: ./horusec-api/deployments/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "postgresql"
    restart: always
    container_name: horusec-api
    environment:
      HORUSEC_PORT: "8000"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_GRPC_AUTH_URL: "horusec-auth:8007"
      HORUSEC_DISABLED_BROKER: "true"
  horusec-manager:
    build:
      context: ../../../
      dockerfile: ./horusec-manager/deployments/Dockerfile
    ports:
      - "8043:8080"
    restart: always
    container_name: horusec-manager
