FROM golang:latest

COPY . /go/src/github.com/ZupIT/horusec
WORKDIR /go/src/github.com/ZupIT/horusec

RUN go get -t -v -u ./horusec-account/...

EXPOSE 8003

CMD ["go", "run", "horusec-account/cmd/app/main.go"]