FROM golang:latest

WORKDIR /go/src/github.com/ZupIT/horusec

COPY . .

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -o /tmp/account ./horusec-account/cmd/app/main.go" -command="/tmp/account"