// Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Horusec",
            "url": "https://github.com/ZupIT/horusec",
            "email": "horusec@zup.com.br"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/dashboard/companies/{companyID}/all-vulnerabilities": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get total vulnerabilities by severity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Company"
                ],
                "operationId": "company-vulnerabilities-by-severity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/details": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get vuln details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Company"
                ],
                "operationId": "vuln-details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "graphql query string",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "graphql query string",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "graphql query string",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/repositories/{repositoryID}/all-vulnerabilities": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get vuln by severity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Repository"
                ],
                "operationId": "repository-by-severity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repositoryID of the repository",
                        "name": "repositoryID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/repositories/{repositoryID}/total-developers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get total developers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Repository"
                ],
                "operationId": "repository-total-dev",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repositoryID of the repository",
                        "name": "repositoryID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/repositories/{repositoryID}/total-repositories": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get total repositories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Repository"
                ],
                "operationId": "repository-total-repositories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repositoryID of the repository",
                        "name": "repositoryID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/repositories/{repositoryID}/vulnerabilities-by-author": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get vuln by developer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Repository"
                ],
                "operationId": "repository-by-developer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repositoryID of the repository",
                        "name": "repositoryID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/repositories/{repositoryID}/vulnerabilities-by-language": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get vuln by language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Repository"
                ],
                "operationId": "repository-by-language",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repositoryID of the repository",
                        "name": "repositoryID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/repositories/{repositoryID}/vulnerabilities-by-repository": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get vuln by repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Repository"
                ],
                "operationId": "repository-by-repository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repositoryID of the repository",
                        "name": "repositoryID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/repositories/{repositoryID}/vulnerabilities-by-time": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get vuln by time",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Repository"
                ],
                "operationId": "repository-by-time",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repositoryID of the repository",
                        "name": "repositoryID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/total-developers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get total developers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Company"
                ],
                "operationId": "company-total-dev",
                "parameters": [
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/total-repositories": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get total repositories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Company"
                ],
                "operationId": "company-total-repositories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/vulnerabilities-by-author": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get total vulnerabilities by author",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Company"
                ],
                "operationId": "company-vulnerabilities-by-author",
                "parameters": [
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/vulnerabilities-by-language": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get total vulnerabilities by language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Company"
                ],
                "operationId": "company-vulnerabilities-by-language",
                "parameters": [
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/vulnerabilities-by-repository": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get total vulnerabilities by repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Company"
                ],
                "operationId": "company-vulnerabilities-by-repository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/dashboard/companies/{companyID}/vulnerabilities-by-time": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get total vulnerabilities by time",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard Company"
                ],
                "operationId": "company-vulnerabilities-by-time",
                "parameters": [
                    {
                        "type": "string",
                        "description": "companyID of the company",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "initialDate query string",
                        "name": "initialDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "finalDate query string",
                        "name": "finalDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "BAD REQUEST"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR"
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Check if Health of service it's OK!",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "operationId": "health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "content": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "content": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "content": {
                    "type": "object"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Horusec-Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Horusec-Analytic",
	Description: "Service of Horusec.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
