FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

RUN apk add --no-cache bash jq openssh-client alpine-sdk

LABEL org.label-schema.schema-version="1.0" \
    org.label-schema.name="NetCore 3.1 Base Image" \
    org.label-schema.vendor="NetCore" \
    org.opencontainers.image.created="2020-04-08 00:00:00-08:00"
