BEGIN;

DROP TABLE IF EXISTS accounts CASCADE;

DROP TABLE IF EXISTS companies CASCADE;

DROP TABLE IF EXISTS account_company CASCADE;

DROP TABLE IF EXISTS repositories CASCADE;

DROP TABLE IF EXISTS account_repository CASCADE;

COMMIT;
