name: Security Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  appsec-workflow:
    uses: ZupIT/appsec-workflow/.github/workflows/appsec-workflow.yml@v1.3.1
    with:
      debug: false
      repository: ${{github.event.repository.name}}
      organization: ${{github.repository_owner}}
      environment: develop
    secrets:
      report-secret: ${{ secrets.VULN_MNG_REPORT_KEY }}
