name: SecurityPipeline

on:
  pull_request:
    branches: [ "**" ]

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Running Horusec Security Download latest version
        shell: bash
        env:
          HORUSEC_CLI_REPOSITORY_AUTHORIZATION: ${{ secrets.HORUSEC_CLI_REPOSITORY_AUTHORIZATION }}
          HORUSEC_CLI_HORUSEC_API_URI: ${{ secrets.HORUSEC_CLI_HORUSEC_API_URI }}
        run: |
          curl -fsSL https://horusec.io/bin/install.sh | bash
          horusec start -p="./" -e="true"
