name: SyncRepositories

on:
  push:
    branches: ["staging"]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code open source
        uses: actions/checkout@master
        with:
          path: tmp-open-source
          ref: staging
      - name: Check out code internal
        uses: actions/checkout@master
        with:
          repository: ZupIT/horusec-internal
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          path: tmp-internal
          ref: develop
      - name: deploy
        run: |
          ls ./
          echo =======================================
          ls ./tmp-open-source
          echo =======================================
          ls ./tmp-open-source/deployments
          echo =======================================
          ls ./tmp-open-source/deployments/scripts
          cp ./tmp-open-source/deployments/scripts/sync-internal.sh ./sync-internal.sh
          chmod +x ./sync-internal.sh
          ./sync-internal.sh "develop" false
          cd tmp-internal
          git status
      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v4
      #   with:
      #     cwd: './internal'
      #     author_name: "Horusec"
      #     author_email: "horusec@zup.com.br"
      #     message: "[skip cicd] update versioning file"
      #     GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
